# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Colors
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Status bar >>
set-option -g status-position bottom
set -g status-style 'bg=default'
set -g status-right ""
bind-key s set-option status # toggle status bar, replaces default "Choose a session from a list"

# Misc
set -g mouse on
set -sg escape-time 0
set-option -g history-limit 100000
set-option -g default-shell /usr/bin/zsh
bind C-l send-keys 'C-l'
set -g detach-on-destroy off
set -g renumber-windows on
set -g set-clipboard on
bind-key -T copy-mode-vi Escape send-keys -X cancel
bind -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind r source-file ~/.config/tmux/tmux.conf
set-option -g focus-events on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Sane split bindings
bind v split-window -h
bind b split-window -v

# Disable auto rename of window
set-option -g allow-rename off

# Status bar visuals
set -g status-left ''

# Better window resize
bind-key -n M-Down resize-pane -U 5
bind-key -n M-Up resize-pane -D 5
bind-key -n M-Left resize-pane -L 5
bind-key -n M-Right resize-pane -R 5

# Better window navigation
bind-key -n C-k select-pane -U
bind-key -n C-j select-pane -D
bind-key -n C-h select-pane -L
bind-key -n C-l select-pane -R

# Better window reposition
bind h splitw -fhb \; swapp -t ! \; killp -t !
bind l splitw -fh  \; swapp -t ! \; killp -t !
bind j splitw -fv  \; swapp -t ! \; killp -t !
bind k splitw -fvb \; swapp -t ! \; killp -t !

# Prefix
set -g prefix C-a
bind C-a send-prefix

# Enable Plugins
run '~/.tmux/plugins/tpm/tpm'
