# Plugins

# "christoomey/vim-tmux-navigator"
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Move current window left/right in order
bind -n M-[ swap-window -t -1  # Alt + [ moves window left
bind -n M-] swap-window -t +1  # Alt + ] moves window right

# Colors
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:RGB"

# Status bar >>
set-option -g status-position bottom
set -g status-style 'bg=default'
set -g status-right ""
bind-key s set-option status # toggle status bar, replaces default "Choose a session from a list"

# Misc
set -g mouse on
set -sg escape-time 0
set-option -g history-limit 100000
set-option -g default-shell /bin/zsh
bind C-l send-keys 'C-l'
set -g detach-on-destroy off
set -g renumber-windows on
set -g set-clipboard on
bind-key -T copy-mode-vi Escape send-keys -X cancel
bind -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
bind r source-file ~/.config/tmux/tmux.conf
set-option -g focus-events on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Sane split bindings
bind v split-window -h
bind b split-window -v

# Disable auto rename of window
set-option -g allow-rename off

# Status bar visuals
set -g status-left ''

# Better window resize
bind-key -n M-h resize-pane -L 5   # left
bind-key -n M-j resize-pane -D 5   # down
bind-key -n M-k resize-pane -U 5   # up
bind-key -n M-l resize-pane -R 5   # right

# Better window reposition
bind h splitw -fhb \; swapp -t ! \; killp -t !
bind l splitw -fh  \; swapp -t ! \; killp -t !
bind j splitw -fv  \; swapp -t ! \; killp -t !
bind k splitw -fvb \; swapp -t ! \; killp -t !

# Prefix
set -g prefix C-a
bind C-a send-prefix
